name: Awesome Linter

on: 
  pull_request:
  workflow_dispatch:
  push:
    branches: main
    paths: README.md

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  awesome-lint:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "linting: README.md"
        run: npx -y awesome-lint
