
name: Post Ads

on:
  workflow_dispatch:
  schedule:
    - cron: "00 14 1 * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  post-ads:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      RTOOT_USER: ${{ secrets.RTOOT_USER }}
      RTOOT_DEFAULT_TOKEN: ${{ secrets.RTOOT_DEFAULT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::rtweet, any::httpuv, github::schochastics/rtoot
      - name: Post Tweet/Toot
        run: Rscript .github/assets/post-ads.R
